apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
          - name: JAEGER_AGENT_HOST
            value: fady-traces-agent.observability.svc.cluster.local
          name: backend
          image: fadyrefaat/dashboard-backend:latest
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "256m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend
      port: 8081
      targetPort: 8080
      nodePort: 30001
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend
    path: /metrics
    interval: 20s
  namespaceSelector:
    matchNames:
    - default